# Test against this version of Node.js
environment:
  matrix:
  - nodejs_version: "4.0"
  - nodejs_version: "4"
  - nodejs_version: "5.0"
  - nodejs_version: "5"

# Install scripts. (runs after repo cloning)
install:
  - cinst imagemagick
  - ps: $env:Path += ";$((Get-ChildItem $env:programfiles | Where-Object {$_.PSIsContainer -eq $true -and $_.Name -match "imagemagick"}).FullName)"
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off
